name: rag_flutter_app
description: "A new Flutter project."

# Prevent this package from being published to pub.dev
publish_to: 'none'

# The current version of the app
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2               # For HTTP requests
  cupertino_icons: ^1.0.8    # iOS-styled icons
  flutter_sound: ^9.2.13     # Audio recording and playback
  permission_handler: ^10.4.5 # For managing app permissions
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter             # For testing
  flutter_lints: ^5.0.0      # Linting rules for Flutter

flutter:
  uses-material-design: true # Use Material Design widgets

  # Declare assets used in the app
  assets:
    - assets/logo.png
    - assets/voice_chat.png